#!/bin/bash
awk '
/^fun DownloadSelectionSheet\(/ {
    in_func = 1
    print "@OptIn(ExperimentalMaterial3Api::class)"
    print "@Composable"
    print "fun DownloadSelectionSheet("
    print "    videoStreams: List<StreamItem>,"
    print "    audioStreams: List<StreamItem>,"
    print "    onDismiss: () -> Unit,"
    print "    onDownload: (StreamItem, Boolean, Boolean) -> Unit // stream, isAudioOnly, saveToDevice"
    print ") {"
    print "    var saveToDevice by remember { mutableStateOf(false) }"
    print "    ModalBottomSheet("
    print "        onDismissRequest = onDismiss,"
    print "        dragHandle = { BottomSheetDefaults.DragHandle() }"
    print "    ) {"
    print "        LazyColumn("
    print "            modifier = Modifier.fillMaxWidth().padding(bottom = 32.dp)"
    print "        ) {"
    print "            item {"
    print "                Text("
    print "                    text = stringResource(R.string.download_quality),"
    print "                    style = MaterialTheme.typography.titleLarge,"
    print "                    fontWeight = FontWeight.Bold,"
    print "                    modifier = Modifier.padding(horizontal = 16.dp, vertical = 8.dp)"
    print "                )"
    print "            }"
    print "            item {"
    print "                Row("
    print "                    modifier = Modifier.fillMaxWidth().padding(horizontal = 16.dp, vertical = 8.dp),"
    print "                    horizontalArrangement = Arrangement.spacedBy(8.dp)"
    print "                ) {"
    print "                    FilterChip("
    print "                        selected = !saveToDevice,"
    print "                        onClick = { saveToDevice = false },"
    print "                        label = { Text(\"VibeTube\") },"
    print "                        leadingIcon = { Icon(Icons.Default.Save, contentDescription = null) }"
    print "                    )"
    print "                    FilterChip("
    print "                        selected = saveToDevice,"
    print "                        onClick = { saveToDevice = true },"
    print "                        label = { Text(\"Device\") },"
    print "                        leadingIcon = { Icon(Icons.Default.PhoneAndroid, contentDescription = null) }"
    print "                    )"
    print "                }"
    print "            }"
    print "            if (videoStreams.isNotEmpty()) {"
    print "                item {"
    print "                    SectionHeader(title = stringResource(R.string.video), icon = Icons.Default.VideoFile)"
    print "                }"
    print "                items(videoStreams) { stream ->"
    print "                    StreamListItem(stream = stream, onDownload = { onDownload(it, false, saveToDevice) })"
    print "                }"
    print "            }"
    print "            if (audioStreams.isNotEmpty()) {"
    print "                item {"
    print "                    SectionHeader(title = \"Audio\", icon = Icons.Default.Audiotrack)"
    print "                }"
    print "                val uniqueAudio = audioStreams.distinctBy { it.format }.sortedByDescending { it.quality.filter { c -> c.isDigit() }.toIntOrNull() ?: 0 }"
    print "                items(uniqueAudio) { stream ->"
    print "                    StreamListItem(stream = stream, onDownload = { onDownload(it, true, saveToDevice) })"
    print "                }"
    print "            }"
    print "        }"
    print "    }"
    print "}"
    next
}
in_func && /^}/ {
    in_func = 0
    next
}
in_func { next }
{ print }
' app/src/main/java/com/rahul/vibetube/ui/components/SelectionSheets.kt > temp.kt && mv temp.kt app/src/main/java/com/rahul/vibetube/ui/components/SelectionSheets.kt
